### ISSUE TITLE
Does it provide database creation operation?

### ISSUE THREAD

**Issue by Ranzeplay** [jeff-miller/sormula#8]

**Comment by jeff-miller** [comment]
It does not provide database creation operations. Currently provides support for select, insert, update, and delete operations.

**Comment by jeff-miller** [comment]
I have considered it but DDL for databases are not always standard. Additional data would be needed in the annotations, for example size of char column, foreign key relationships, not null constraints, number precision/scale, etc., which clutter the Java. Maybe the DDL specific stuff could be located outside of the Java class records. What would be some examples of what you had in mind?

**Comment by Ranzeplay** [comment]
Like creating a table if it doesn't exist.
